//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Five_Seconds.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Five_Seconds.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddRingtone {
            get {
                return ResourceManager.GetString("AddRingtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Off Option.
        /// </summary>
        internal static string AlarmOffOption {
            get {
                return ResourceManager.GetString("AlarmOffOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Option.
        /// </summary>
        internal static string AlarmOption {
            get {
                return ResourceManager.GetString("AlarmOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Record (Month).
        /// </summary>
        internal static string AlarmRecord_Month {
            get {
                return ResourceManager.GetString("AlarmRecord_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Record (Week).
        /// </summary>
        internal static string AlarmRecord_Week {
            get {
                return ResourceManager.GetString("AlarmRecord_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Setting.
        /// </summary>
        internal static string AlarmSetting {
            get {
                return ResourceManager.GetString("AlarmSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Sound.
        /// </summary>
        internal static string AlarmSound {
            get {
                return ResourceManager.GetString("AlarmSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringtone Setting.
        /// </summary>
        internal static string AlarmSoundSetting {
            get {
                return ResourceManager.GetString("AlarmSoundSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Second Rule Alarm.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this record?.
        /// </summary>
        internal static string AskDeleteRecord {
            get {
                return ResourceManager.GetString("AskDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to allow the app to access your photos, media, and files on your device?.
        /// </summary>
        internal static string AskMediaPermission {
            get {
                return ResourceManager.GetString("AskMediaPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the five second rule~.
        /// </summary>
        internal static string Brief_01 {
            get {
                return ResourceManager.GetString("Brief_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let`s make an alarm.
        /// </summary>
        internal static string Brief_02 {
            get {
                return ResourceManager.GetString("Brief_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Alarm sounds!.
        /// </summary>
        internal static string Brief_03 {
            get {
                return ResourceManager.GetString("Brief_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What if voice recognition is wrong?.
        /// </summary>
        internal static string Brief_04 {
            get {
                return ResourceManager.GetString("Brief_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ll count five seconds!.
        /// </summary>
        internal static string Brief_05 {
            get {
                return ResourceManager.GetString("Brief_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want know ablut five second rules?.
        /// </summary>
        internal static string Brief_06 {
            get {
                return ResourceManager.GetString("Brief_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I`ll show you how to use our application.
        /// </summary>
        internal static string Brief_Detail_01 {
            get {
                return ResourceManager.GetString("Brief_Detail_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the + button on the top right of the main screen and add an alarm..
        /// </summary>
        internal static string Brief_Detail_02 {
            get {
                return ResourceManager.GetString("Brief_Detail_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the alarm rings, press the microphone button and tell your phone the &apos;alarm name&apos;!.
        /// </summary>
        internal static string Brief_Detail_03 {
            get {
                return ResourceManager.GetString("Brief_Detail_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the alarm name in the text box and press the start button..
        /// </summary>
        internal static string Brief_Detail_04 {
            get {
                return ResourceManager.GetString("Brief_Detail_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start immediately before the 5 second count is over!.
        /// </summary>
        internal static string Brief_Detail_05 {
            get {
                return ResourceManager.GetString("Brief_Detail_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Search for 5 second rules on Google.
        /// </summary>
        internal static string Brief_Detail_06 {
            get {
                return ResourceManager.GetString("Brief_Detail_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 secodnds rule brief description.
        /// </summary>
        internal static string BriefDescription {
            get {
                return ResourceManager.GetString("BriefDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to success.
        /// </summary>
        internal static string ChangeSuccess {
            get {
                return ResourceManager.GetString("ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure the alarm was successful?.
        /// </summary>
        internal static string ChangeSuccessDetail {
            get {
                return ResourceManager.GetString("ChangeSuccessDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record.
        /// </summary>
        internal static string DeleteRecord {
            get {
                return ResourceManager.GetString("DeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denial.
        /// </summary>
        internal static string Denial {
            get {
                return ResourceManager.GetString("Denial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not delay alarm.
        /// </summary>
        internal static string DoNotDelayAlarm {
            get {
                return ResourceManager.GetString("DoNotDelayAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This alarm can only be turned off by voice recognition and cannot be delayed..
        /// </summary>
        internal static string DoNotDelayAlarmDescription {
            get {
                return ResourceManager.GetString("DoNotDelayAlarmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyday.
        /// </summary>
        internal static string Everyday {
            get {
                return ResourceManager.GetString("Everyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count five seconds.
        /// </summary>
        internal static string FiveCount {
            get {
                return ResourceManager.GetString("FiveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to start counting 5 seconds?.
        /// </summary>
        internal static string FiveCountDetail {
            get {
                return ResourceManager.GetString("FiveCountDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You forgot the alarm name!.
        /// </summary>
        internal static string ForgotAlarmName {
            get {
                return ResourceManager.GetString("ForgotAlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set the app to link..
        /// </summary>
        internal static string ForgotLinkOtherApps {
            get {
                return ResourceManager.GetString("ForgotLinkOtherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You forgot the &apos;Words that wake me up&apos;.
        /// </summary>
        internal static string ForgotWordsThatWakeMeUp {
            get {
                return ResourceManager.GetString("ForgotWordsThatWakeMeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Copyright.
        /// </summary>
        internal static string IconCopyright {
            get {
                return ResourceManager.GetString("IconCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indomitable Alarm.
        /// </summary>
        internal static string IndomitableAlarm {
            get {
                return ResourceManager.GetString("IndomitableAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link other apps.
        /// </summary>
        internal static string LinkOtherApps {
            get {
                return ResourceManager.GetString("LinkOtherApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app you set opens after a successful alarm..
        /// </summary>
        internal static string LinkOtherAppsDescription {
            get {
                return ResourceManager.GetString("LinkOtherAppsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All alarms are off.
        /// </summary>
        internal static string NoNextAlarm {
            get {
                return ResourceManager.GetString("NoNextAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record.
        /// </summary>
        internal static string NoRecord {
            get {
                return ResourceManager.GetString("NoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit.
        /// </summary>
        internal static string Permit {
            get {
                return ResourceManager.GetString("Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write alarm name.
        /// </summary>
        internal static string PleaseAlarmName {
            get {
                return ResourceManager.GetString("PleaseAlarmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query count exceeded.
        /// </summary>
        internal static string QueryCountExceeded {
            get {
                return ResourceManager.GetString("QueryCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only seven queries are allowed..
        /// </summary>
        internal static string QueryCountExceededDetail {
            get {
                return ResourceManager.GetString("QueryCountExceededDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Option.
        /// </summary>
        internal static string RecordOption {
            get {
                return ResourceManager.GetString("RecordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringing Soon.
        /// </summary>
        internal static string RingingSoon {
            get {
                return ResourceManager.GetString("RingingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You set the time past!.
        /// </summary>
        internal static string SetTimePast {
            get {
                return ResourceManager.GetString("SetTimePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple alarm.
        /// </summary>
        internal static string SimpleAlarm {
            get {
                return ResourceManager.GetString("SimpleAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can dismiss the alarm with a simple touch..
        /// </summary>
        internal static string SimpleAlarmDescription {
            get {
                return ResourceManager.GetString("SimpleAlarmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no record~.
        /// </summary>
        internal static string ThereIsNoRecord {
            get {
                return ResourceManager.GetString("ThereIsNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string Vibration {
            get {
                return ResourceManager.GetString("Vibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Alarm.
        /// </summary>
        internal static string VoiceAlarm {
            get {
                return ResourceManager.GetString("VoiceAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This alarm can only be turned off by voice recognition..
        /// </summary>
        internal static string VoiceAlarmDescription {
            get {
                return ResourceManager.GetString("VoiceAlarmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Recognition.
        /// </summary>
        internal static string VoiceRecognition {
            get {
                return ResourceManager.GetString("VoiceRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the alarm sounds, the sentence is spoken out every 12 seconds..
        /// </summary>
        internal static string WakeUpTextDescription {
            get {
                return ResourceManager.GetString("WakeUpTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex) Wake Up! OO!!.
        /// </summary>
        internal static string WakeUpTextSample {
            get {
                return ResourceManager.GetString("WakeUpTextSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        internal static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekend.
        /// </summary>
        internal static string Weekend {
            get {
                return ResourceManager.GetString("Weekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the 5 second rule?.
        /// </summary>
        internal static string WhatFiveSecondsRule {
            get {
                return ResourceManager.GetString("WhatFiveSecondsRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words that wake me up.
        /// </summary>
        internal static string WordsThatWakeMeUp {
            get {
                return ResourceManager.GetString("WordsThatWakeMeUp", resourceCulture);
            }
        }
    }
}
